server:
  port: 8080
  tomcat:
    basedir: /home/fileyun/tomcat

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

file:
  upload:
    dir: /mnt/yun

logging:
  path: /mnt/log/file-api

